BEGIN;

DROP TABLE IF EXISTS "team_pokemon", "pokemon_type", "team", "type", "pokemon", "user";

CREATE TABLE "user" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "name" VARCHAR(255) NOT NULL,
  "pseudo" VARCHAR(100) NOT NULL UNIQUE,
  "password" VARCHAR(255) NOT NULL
);

CREATE TABLE "pokemon" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL UNIQUE,
  "hp" INT NOT NULL,
  "atk" INT NOT NULL,
  "def" INT NOT NULL,
  "atk_spe" INT NOT NULL,
  "def_spe" INT NOT NULL,
  "speed" INT NOT NULL
);

CREATE TABLE "type" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL,
  "color" VARCHAR(7) NOT NULL
);

CREATE TABLE "team" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "user_id" INT NOT NULL REFERENCES "user"("id")
);

CREATE TABLE "pokemon_type" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "pokemon_id" INT NOT NULL REFERENCES "pokemon"("id") ON DELETE CASCADE,
  "type_id" INT NOT NULL REFERENCES "type"("id") ON DELETE CASCADE,
  UNIQUE ("pokemon_id", "type_id")
);

CREATE TABLE "team_pokemon" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "pokemon_id" INT NOT NULL REFERENCES "pokemon"("id") ON DELETE CASCADE,
  "team_id" INT NOT NULL REFERENCES "team"("id") ON DELETE CASCADE,
  UNIQUE ("pokemon_id", "team_id")
);

COMMIT;