

### Création d'une team
POST http://localhost:3000/teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc3Mzg1NTg3MiwiZXhwIjoxNzczODYzMDcyfQ.XeXrcKpWHMyEcCWnXcuI__JZz20ZdEg5EfgQjVNxy-E

{
   "name": "Ma team user_ok",
  "user_id": 1
}


### Récupération d'une team
GET http://localhost:3000/teams/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc3Mzg0ODU5MywiZXhwIjoxNzczODU1NzkzfQ.Ggf4D-WI3gAMtOL1Ad0Kt9KnyNYtb-BNdaybzaBQoPk



### Suppression d'une team
DELETE http://localhost:3000/teams/4



### Modification d'une team
PUT http://localhost:3000/teams/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc3Mzg1NTg3MiwiZXhwIjoxNzczODYzMDcyfQ.XeXrcKpWHMyEcCWnXcuI__JZz20ZdEg5EfgQjVNxy-E

{
  "name": "Team test bidouille bon user"
}


### Test erreur création (sans user_id)
POST http://localhost:3000/teams
Content-Type: application/json

{
  "name": "étrange "
}

###Test ajout d'un pokemon dans un team
POST http://localhost:3000/teams/7/pokemon/9
Content-Type: application/json


###Test suppréssion d'un pokemon dans un team
DELETE http://localhost:3000/teams/7/pokemon/9
Content-Type: application/json


###Test inscription d'un user
POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "Francois",
  "email": "francois@test.com",
  "pseudo": "francois",
  "password": "azerty123"
}

###Test d'autentification d'un user
POST http://localhost:3000/login
Content-Type: application/json

{
   "email": "francois@test.com",
  "password": "azerty123"
}