### Create a team
POST http://localhost:3000/teams
Content-Type: application/json
Authorization: Bearer TON_TOKEN_ICI

{
  "name": "Ma team user ok"
}

### Get one team
GET http://localhost:3000/teams/7

### Delete a team
DELETE http://localhost:3000/teams/4
Authorization: Bearer TON_TOKEN_ICI

### Update a team
PUT http://localhost:3000/teams/10
Content-Type: application/json
Authorization: Bearer TON_TOKEN_ICI

{
  "name": "Updated team name"
}

### Create team - missing name
POST http://localhost:3000/teams
Content-Type: application/json
Authorization: Bearer TON_TOKEN_ICI

{
}

### Create team - missing token
POST http://localhost:3000/teams
Content-Type: application/json

{
  "name": "Unauthorized team"
}

### Add a pokemon to a team
POST http://localhost:3000/teams/11/pokemon/19
Authorization: Bearer TON_TOKEN_ICI

### Remove a pokemon from a team
DELETE http://localhost:3000/teams/7/pokemon/9
Authorization: Bearer TON_TOKEN_ICI

### Register a user
POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "Francois",
  "email": "francois@test.com",
  "pseudo": "francois",
  "password": "Azerty123"
}

### Login a user
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "francois@test.com",
  "password": "Azerty123"
}

### Login - invalid credentials
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "francois@test.com",
  "password": "WrongPassword123"
}

### Get one team - invalid id
GET http://localhost:3000/teams/abc